export type ConsentState = { analytics: boolean; marketing: boolean };
export type AnalyticsConfig = { gaId: string; metaPixelId: string; contactEndpoint: string };
export const CONSENT_KEY = 'vizio-consent-v2';
const UTM_KEY = 'vizio-campaign';
const UTM_FIELDS = ['utm_source','utm_medium','utm_campaign','utm_content','utm_term'] as const;
declare global { interface Window { dataLayer?: unknown[]; gtag?: (...args:unknown[])=>void; fbq?: (...args:unknown[])=>void; __VIZIO_CONFIG__: AnalyticsConfig; } }
export function getConsent(): ConsentState | null { try { const stored=localStorage.getItem(CONSENT_KEY); return stored?JSON.parse(stored):null; } catch { return null; } }
export function setConsent(consent: ConsentState) { localStorage.setItem(CONSENT_KEY,JSON.stringify(consent)); window.dispatchEvent(new CustomEvent('vizio:consent-changed',{detail:consent})); }
export function captureCampaign() { const params=new URLSearchParams(location.search); const campaign:Record<string,string>={}; UTM_FIELDS.forEach((key)=>{const value=params.get(key);if(value)campaign[key]=value;}); if(Object.keys(campaign).length){campaign.landing_page=location.href;campaign.referrer=document.referrer;sessionStorage.setItem(UTM_KEY,JSON.stringify(campaign));} }
export function campaignFields(): Record<string,string> { let stored:Record<string,string>={}; try{stored=JSON.parse(sessionStorage.getItem(UTM_KEY)||'{}');}catch{} return {landing_page:location.href,referrer:document.referrer,...stored}; }
export function populateTrackingFields(form:HTMLFormElement){const fields=campaignFields();form.querySelectorAll<HTMLInputElement>('[data-tracking-field]').forEach((input)=>{input.value=fields[input.name]||'';});}
export function trackEvent(name:string,params:Record<string,unknown>={}){window.gtag?.('event',name,params);if(window.fbq){const standard=name.includes('form_submit')?'Lead':name==='phone_click'||name==='email_click'?'Contact':'';window.fbq('trackCustom',name,params);if(standard)window.fbq('track',standard,params);}}
function loadGa(id:string){if(!id||document.querySelector('[data-vizio-ga]'))return;const s=document.createElement('script');s.async=true;s.src=`https://www.googletagmanager.com/gtag/js?id=${encodeURIComponent(id)}`;s.dataset.vizioGa='';document.head.appendChild(s);window.dataLayer=window.dataLayer||[];window.gtag=(...args:unknown[])=>window.dataLayer?.push(args);window.gtag('js',new Date());window.gtag('config',id);}
function loadMeta(id:string){if(!id||document.querySelector('[data-vizio-meta]'))return;const s=document.createElement('script');s.async=true;s.src='https://connect.facebook.net/en_US/fbevents.js';s.dataset.vizioMeta='';const queue:unknown[][]=[];const fbq:any=(...args:unknown[])=>fbq.callMethod?fbq.callMethod(...args):queue.push(args);Object.assign(fbq,{queue,push:fbq,loaded:true,version:'2.0'});window.fbq=fbq;document.head.appendChild(s);fbq('init',id);fbq('track','PageView');}
function applyConsent(config:AnalyticsConfig){const consent=getConsent();if(!consent)return;if(consent.analytics)loadGa(config.gaId);if(consent.marketing)loadMeta(config.metaPixelId);}
async function submitForm(form:HTMLFormElement,config:AnalyticsConfig){const status=form.querySelector<HTMLElement>('[data-form-status]');const button=form.querySelector<HTMLButtonElement>('button[type="submit"]');const eventBase=form.dataset.formEvent||'contact_form';populateTrackingFields(form);trackEvent(`${eventBase}_submit`,{service:new FormData(form).get('service')||''});if(!config.contactEndpoint){if(status)status.textContent='A levelezőprogram megnyitása…';return;}if(button){button.disabled=true;button.classList.add('loading');}if(status){status.textContent='Küldés folyamatban…';status.className='form-status';}try{const response=await fetch(config.contactEndpoint,{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}});if(!response.ok)throw new Error('submit_failed');form.reset();if(status){status.textContent='Köszönjük a megkeresést! Hamarosan felvesszük veled a kapcsolatot.';status.classList.add('success');}}catch{if(status){status.textContent='Az üzenetet most nem sikerült elküldeni. Kérjük, írj nekünk e-mailt vagy próbáld újra később.';status.classList.add('error');}}finally{if(button){button.disabled=false;button.classList.remove('loading');}}}
export function initAnalytics(config:AnalyticsConfig){captureCampaign();applyConsent(config);window.addEventListener('vizio:consent-changed',()=>applyConsent(config));document.addEventListener('click',(event)=>{const link=(event.target as HTMLElement).closest<HTMLAnchorElement>('a');if(!link)return;const name=link.dataset.event||(link.href.startsWith('tel:')?'phone_click':link.href.startsWith('mailto:')?'email_click':'');if(name)trackEvent(name,{path:location.pathname,label:link.textContent?.trim()});});document.querySelectorAll<HTMLFormElement>('.tracked-form').forEach((form)=>{populateTrackingFields(form);let started=false;form.addEventListener('focusin',()=>{if(!started){started=true;trackEvent(`${form.dataset.formEvent||'contact_form'}_start`);}});form.addEventListener('submit',(event)=>{if(config.contactEndpoint)event.preventDefault();submitForm(form,config);});});}
